Coins Added
lugvitc/lugvitc-ctf pull request #19
Opened 2024-01-16 14:07 UTC by ShashwatMishra2411

2024-01-16 14:37 UTC, WizzyGeek requested changes

2024-01-16 14:37 UTC, WizzyGeek commented on src/components/preevent/Question.tsx
> +						localStorage.setItem("coins", JSON.stringify(res.data));
res.data.coins

2024-01-16 20:00 UTC, WizzyGeek requested changes

2024-01-16 20:00 UTC, WizzyGeek commented on src/components/preevent/Question.tsx
>  				regNo: regNo,
`tag: regNo`

2024-01-17 09:53 UTC, Zeref101 approved these changes

2024-01-17 09:55 UTC, WizzyGeek approved these changes

2024-01-17 09:55 UTC, merged