Navbar and landing page added
lugvitc/lugvitc-ctf pull request #4
Opened 2023-12-23 15:29 UTC by Zeref101

Navbar with native view, mobile view and tablet view added
landing page with responsiveness added
type->index.ts for type of links created
constants->index.ts for the navbar links created
custom tailwind classes created

2023-12-23 16:17 UTC, WizzyGeek approved these changes

2023-12-23 16:47 UTC, nexxeln requested changes
we have a lot of hardcoded hex values, would be better to extract them into css variables and then referencing them in our tailwind config so that we can use an abstracted class to use those colours.

2023-12-23 16:47 UTC, nexxeln commented on src/components/LeftSideBar.tsx
> +									: "text-dark300_light900"
i think there's a mistake here, `text-dark300z_light900`?

2023-12-25 16:49 UTC, WizzyGeek commented
@Zeref101 can you run `npm run format` and commit to pass the linting check?

2023-12-25 16:55 UTC, WizzyGeek commented
Also correct me if I am wrong, but I don't think this is quite what @nexxeln described.

I am not quite fond of it too.

@nexxeln what's your opinion?

2023-12-26 15:35 UTC, nexxeln requested changes
okay yeah this im not a big fan of. what i meant was to put the colors we're using throughout the project in the `theme` object of the tailwind config. see these [docs on extending the tailwind config](https://tailwindcss.com/docs/theme#extending-the-default-theme

after you've done that revert back to what we had before, we don't need to over abstract our tailwind classes.

2023-12-26 16:36 UTC, WizzyGeek commented
@Zeref101 please revert the last 3 commits

2023-12-26 16:40 UTC, WizzyGeek commented
Just `git reset --hard 0a52fce && git push --force` will work good

2023-12-27 10:54 UTC, WizzyGeek approved these changes
Let's extract the colours into variables in another PR.

2023-12-27 10:54 UTC, WizzyGeek commented on tailwind.config.js
> +	],
Revert this to what we had earlier

2023-12-27 12:57 UTC, nexxeln approved these changes
lgtm

2023-12-27 12:57 UTC, nexxeln commented
interesting we're getting a build error

2023-12-27 13:04 UTC, nexxeln requested changes

2023-12-27 13:04 UTC, nexxeln commented on tailwind.config.js
> +		},
this `colors` object should be in the `extend`

2023-12-27 14:01 UTC, nexxeln approved these changes
lgtm, great work!

2023-12-27 14:01 UTC, merged